<?php
/**
 * @link http://www.php-devil.ru/
 * @copyright Copyright (c) 2017 Web Wizardry
 * @license http://www.php-devil.ru/license/
 */

namespace PhpDevil\testing\tests\integrations;
use PhpDevil\testing\mock\migrations\IdenityMigrationMock;
use PhpDevil\testing\tests\_helpers\WebAppTestCase;

class ActiveRecordIdenityTest extends WebAppTestCase
{
    protected function setUp()
    {
        parent::setUp();
        (new IdenityMigrationMock())->up();
    }

    protected function tearDown()
    {
        (new IdenityMigrationMock())->down();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testTableExists()
    {

    }
}