<?php
/**
 * @link http://www.php-devil.ru/
 * @copyright Copyright (c) 2017 Web Wizardry
 * @license http://www.php-devil.ru/license/
 */

namespace PhpDevil\testing\tests\integrations;
use PhpDevil\components\db\Connection;
use PhpDevil\Devil;
use PhpDevil\testing\mock\migrations\IdenityMigrationMock;
use PhpDevil\testing\tests\_helpers\WebAppTestCase;

class ActiveRecordIdenityTest extends WebAppTestCase
{
    private $migration = null;

    protected function setUp()
    {
        Devil::clearServices();
        parent::setUp();
        $this->migration = new IdenityMigrationMock();
        $this->migration->up();
    }

    protected function tearDown()
    {
        $this->migration->down(true);
        $this->migration=null;
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Connection
     */
    protected function db()
    {
        return $this->migration->db();
    }

    public function testSchemaExists()
    {
        $this->assertTrue($this->db()->schema->findTable('phpunit_idenity')->exists);
    }

    public function testTableExists()
    {
        $exists = $this->migration->db()->prepare("show tables like :table")->execute(['table' => 'phpunit_idenity']);
        $this->assertFalse(empty($exists->fetch()));
    }

    public function testTableExists2()
    {
        $this->migration->down();
        $exists = $this->migration->db()->prepare("show tables like :table")->execute(['table' => 'phpunit_idenity']);
        $this->assertTrue(empty($exists->fetch()));
    }

    public function testExceptionOnHardDrop()
    {
        $this->expectException(\PDOException::class);
        $this->migration->down();
        $this->migration->down();
    }
}